name: preview-on-pr
on: pull_request
jobs:
  yaml-schema-validation:
    strategy:
      matrix:
        schema: []
        target: []
        include:
          - schema: 'schemas/software.yml'
            target: 'our-work/software'
            name: 'Software YML Validation'
          - schema: 'schemas/workshops-and-talks.yml'
            target: 'our-work/workshops-and-talks'
            name: 'Workshops YML Validation'
          # - schema: 'schemas/meta-main.yml'
          #   target: 'meta/main'
          #   name: 'Main YML Validation'
          # - schema: 'schemas/meta-category.yml'
          #   target: 'our-work/category'
          #   name: 'Category YML Validation'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.name }}
      uses: nrkno/yaml-schema-validator-github-action@master
      with:
        schema: ${{ matrix.schema }}
        target: ${{ matrix.target }}
        strict: '1'
  build_and_preview:
    runs-on: ubuntu-latest
    needs: [yaml-schema-validation]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: brown-ccv/ccv-website-nuxt
          submodules: recursive
          fetch-depth: 0
      - name: Change content to current commit
        run: cd content && git checkout ${{ github.event.pull_request.head.sha }}
      - name: Install
        run: npm ci 
      - name: Generate Static Content
        run: npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CCV_BROWN_EDU }}'
          projectId: ccv-brown-edu
          expires: 7d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels