name: preview-on-pr
on: pull_request
jobs:
  yaml-validation:
    strategy:
      matrix:
        values:
          - name: 'Meta-Main Validation'
            schema: 'schemas/meta-main.yml'
            target: 'meta/main' 
          - name: 'Meta-Category Validation'
            schema: 'schemas/meta-category.yml'
            target: 'meta/category'
          - name: 'Opportunities Validation'
            schema: 'schemas/opportunities.yml'
            target: 'about/opportunities.yml'
          - name: 'People Validation'
            schema: 'schemas/people.yml'
            target: 'about/people.yml'
          - name: 'Banners Validation'
            schema: 'schemas/banners.yml'
            target: 'banners'
          - name: 'Help Validation'
            schema: 'schemas/meta-category.yml'
            target: 'help'
          - name: 'Collaboration Validation'
            schema: 'schemas/collaborations.yml'
            target: 'our-work/collaborations'
          - name: 'Software Validation'
            schema: 'schemas/software.yml'
            target: 'our-work/software'
          - name: 'Workshops Validation'
            schema: 'schemas/workshops-and-talks.yml'
            target: 'our-work/workshops-and-talks'        
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: ${{ matrix.values.name }}
      uses: nrkno/yaml-schema-validator-github-action@master
      with:
        schema: ${{ matrix.values.schema }}
        target: ${{ matrix.values.target }}
        strict: '1'
  build_and_preview:
    runs-on: ubuntu-latest
    needs: [yaml-validation]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: brown-ccv/ccv-website-nuxt
          submodules: recursive
          fetch-depth: 0
      - name: Change content to current commit
        run: cd content && git checkout ${{ github.event.pull_request.head.sha }}
      - name: Install
        run: npm ci 
      - name: Generate Static Content
        run: npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CCV_BROWN_EDU }}'
          projectId: ccv-brown-edu
          expires: 7d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels