name: preview-on-pr
on: pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: brown-ccv/ccv-website-nuxt
          submodules: recursive
          fetch-depth: 0
      - name: Change content to current commit
        run: cd content && git fetch origin && git checkout ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: npm ci && npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0.5-alpha
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN_MIR }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CCV_BROWN_EDU }}'
          projectId: ccv-brown-edu
          expires: 7d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels